spring:
  application:
    name: chat-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}

  datasource:
    url: jdbc:postgresql://localhost:5434/chat_db
    username: chat_user
    password: chat_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

aws:
  endpoint: ${AWS_ENDPOINT:http://localhost:4566}
  region: ${AWS_REGION:us-east-1}
  sns:
    chat-events-topic-arn: ${AWS_CHAT_EVENTS_TOPIC_ARN:arn:aws:sns:us-east-1:000000000000:chat-events}
  sqs:
    chat-user-events-queue-url: ${AWS_CHAT_USER_EVENTS_QUEUE_URL:http://localhost:4566/000000000000/chat-user-events-queue}

server:
  port: 8082
