version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.0.0
    container_name: chess-localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
      - "5433:5432"            # RDS PostgreSQL port
    environment:
      - SERVICES=sns,sqs,s3,rds
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file:
      - ../.env
    volumes:
      - "../localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
